### ISSUE TITLE
Please add GLIP

### ISSUE THREAD

**Issue by Haotian-Zhang** [TheShadow29/awesome-grounding#19]
Hi, 

Thanks for sharing this great repo. Just want to share some of our recent work GLIP on visual grounding pre-training and I hope they could help this community through your platform. Thank you very much! 

Abstract: This paper presents a grounded language-image pre-training (GLIP) model for learning object-level, language-aware, and semantic-rich visual representations. GLIP unifies object detection and phrase grounding for pre-training. The unification brings two benefits: 1) it allows GLIP to learn from both detection and grounding data to improve both tasks and bootstrap a good grounding model; 2) GLIP can leverage massive image-text pairs by generating grounding boxes in a self-training fashion, making the learned representation semantic-rich. In our experiments, we pre-train GLIP on 27M grounding data, including 3M human-annotated and 24M web-crawled image-text pairs. The learned representations demonstrate strong zero-shot and few-shot transferability to various object-level recognition tasks. 1) When directly evaluated on COCO and LVIS (without seeing any images in COCO during pre-training), GLIP achieves 49.8 AP and 26.9 AP, respectively, surpassing many supervised baselines. 2) After fine-tuned on COCO, GLIP achieves 60.8 AP on val and 61.5 AP on test-dev, surpassing prior SoTA. 3) When transferred to 13 downstream object detection tasks, a 1-shot GLIP rivals with a fully-supervised Dynamic Head. Code will be released at (https://github.com/microsoft/GLIP).

**Comment by TheShadow29** [comment]
@Haotian-Zhang I am aware of GLIP paper (I really liked it!) but didn't have the chance to update the repo in a while. Could you create a pull request? Thanks!

**Comment by Haotian-Zhang** [comment]
@TheShadow29 Thank you for your great interest in our work! I will create a PR right now. Thanks!

**Comment by TheShadow29** [comment]
Thanks I have merged the PR. Closing the issue.
